import { Component } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ResearchBookService } from 'src/app/services/research-book.service'; // Replace 'path-to-research-book-service' with the actual path to your service

@Component({
  selector: 'app-research-book-form',
  templateUrl: './research-book.component.html',
  styleUrls: ['./research-book.component.css']
})
export class ResearchBookComponent {
  researchBookForm!: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private researchBookService: ResearchBookService
  ) {
    this.researchBookForm = this.formBuilder.group({
      title: ['', Validators.required],
      description: ['', Validators.required],
      caseId: ['', Validators.required]
    });
  }

  onSubmit(): void {
    if (this.researchBookForm.valid) {
      const researchBook: any = {
        id: 0, // Generated by the backend
        title: this.researchBookForm.value.title,
        description: this.researchBookForm.value.description,
        caseId: this.researchBookForm.value.caseId,
        userId: 0, // Retrieve the logged-in user's ID
        createdAt: new Date() // Current timestamp
      };

      this.researchBookService.createResearchBook(researchBook).subscribe(
        (response) => {
          // Handle successful research book creation
        },
        (error) => {
          // Handle research book creation error
        }
      );
    }
  }
  getControl(name:any):AbstractControl | null{
    return this.researchBookForm.get(name);
  }
}
